// <auto-generated />
using System;
using DataManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataManager.Migrations
{
    [DbContext(typeof(LotteryDbContext))]
    [Migration("20230913131518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("DataManager.Models.LotteryDraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("LuckyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberFive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberFour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberSix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberThree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberTwo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Draws");
                });
#pragma warning restore 612, 618
        }
    }
}
